backend:
  name: git-gateway
  repo: Ultiblog/irrelevant-subject
  branch: main

media_folder: "content/blog/images"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: 'Created', name: 'created', widget: "date" }
      - { label: "Summary", name: "excerpt", widget: "text" }
      - { label: "Image",name: "image",widget: "image",choose_url: true }
      - { label: "Image Caption", name: "image_caption", widget: "text", required: false }
      - { label: "Author", name: "author", widget: "text" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: 'Blog post content', name: 'content', widget: 'markdown' }
