backend:
  name: git-gateway
  repo: Ultiblog/irrelevant-subject
  branch: main

media_folder: "content/blog/images"
#public_folder: "/assets/blog"

collections:
  - name: "blog"
    label: "Post"
    folder: "content/blog"
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Summary", name: "excerpt", widget: "text" }
      - { label: "Created",name: "created", widget: "date", format: 'YYYY-MM-DD' }
      - { label: "Image",name: "image",widget: "image", choose_url: true }
      - { label: "Image Caption", name: "image_caption", widget: "text" }
      - { label: "Author", name: "author", widget: "list" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: 'Blog post content', name: 'content', widget: 'markdown' }
